In [2]:
import numpy as np

## Numpy arrays

In [3]:
benimListem=[2,3,4]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([2, 3, 4])

In [6]:
matrix=[[1,2,3],[4,8,6],[7,8,9]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 8, 6],
       [7, 8, 9]])

## arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

## zeros, ones

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## linspace, eye

In [13]:
np.linspace(0,20,50)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [15]:
np.random.randn(4)

array([-2.235169  ,  0.70309546, -0.06510417,  1.28041433])

In [16]:
np.random.randn(3,3)

array([[-2.34666329,  0.35326946,  0.52401103],
       [-0.2809574 , -0.35679289,  1.05917622],
       [-2.80851314, -0.44845586, -2.28678678]])

In [17]:
np.random.randint(4,165,5) # ilk boşluğa başlangıç, ikinci boşluğa bitiş, son boşluğa da kaç adet sayı istediğimiz yazılır.

array([ 95,  56,  40, 105,  68])

## Numpy dizi methodları

In [18]:
randomDizi=np.random.randint(0,100,20)

In [19]:
randomDizi

array([50, 51, 89, 82, 31, 89, 16, 76, 25, 50, 25, 98, 73, 54,  5, 45, 62,
       66,  0, 34])

In [23]:
randomDizi.reshape(5,4)

array([[50, 51, 89, 82],
       [31, 89, 16, 76],
       [25, 50, 25, 98],
       [73, 54,  5, 45],
       [62, 66,  0, 34]])

In [25]:
randomDizi.max()

98

In [26]:
randomDizi.min()

0

## matrix

In [27]:
benimListem=[[10,20,30],[20,30,40],[4,5,6]]

In [28]:
benimMatrixDizim=np.array(benimListem)

In [29]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [ 4,  5,  6]])

In [30]:
benimMatrixDizim[0]

array([10, 20, 30])

In [33]:
benimMatrixDizim[1][2]

40

In [34]:
benimMatrixDizim[1,2]

40

## operasyonlar

In [35]:
yeniBirDizi=np.random.randint(1,100,20)

In [36]:
yeniBirDizi

array([59, 74, 17, 77, 38, 65, 46,  4, 52, 17, 84, 75, 53, 16,  4, 79, 83,
       63, 63, 63])

In [39]:
sonucDizisi = yeniBirDizi > 25

In [40]:
yeniBirDizi[sonucDizisi]

array([59, 74, 77, 38, 65, 46, 52, 84, 75, 53, 79, 83, 63, 63, 63])

In [41]:
np.sqrt(sonucDizisi) #karekök alma

array([1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1.], dtype=float16)

In [42]:
np.max(sonucDizisi)

True

In [43]:
np.min(sonucDizisi)

False

In [ ]:
# numpy.org 'ta daha detaylı şekilde methodlara bakılabilir.